# Generated by Django 3.2.3 on 2021-07-11 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_album_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='video_data')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('total_view', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('upload_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
